# Generated by Django 5.0.3 on 2024-04-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/product/p1.jpeg', upload_to='media/images/product_image'),
        ),
    ]
