# Generated by Django 5.0.3 on 2024-04-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/product_image/p1.jpeg', upload_to='images/product_image'),
        ),
    ]
