# Generated by Django 5.0.4 on 2024-05-04 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
