# Generated by Django 5.0.4 on 2024-05-04 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_employee_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=90)),
                ('speed', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
