# Generated by Django 5.0.6 on 2024-06-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('drive_type', models.CharField(choices=[('FWD', 'Front Wheel Drive'), ('RWD', 'Rear Wheel Drive'), ('4WD', 'Four Wheel Drive')], max_length=3)),
                ('desc', models.TextField()),
            ],
        ),
    ]
